### ISSUE TITLE
Issue with the Fn key not letting up

### ISSUE THREAD

**Issue by goeland86** [jukben/Model01-Firmware#1]
Hi @jukben - I got a little lazy with flashing my Model01 with a modified firmware, so decided to use yours (I used default anyway).

The main problem I have, is that when I use the `Fn` key, it "bugs" in that it has inconsistent behavior. It only happens when using the EEPROM-stored LED, not the alternate rainbow color layout.

I can't help debug this as I've too many other irons in the fire, but thought I'd point it out in case you wanted to try and fix it.

Brilliant job on the whole LED selector, I love it, just wish the bug wasn't there.

**Comment by jukben** [comment]
Hey! 🙌 

I'd love to look on it, but I'm 300 Km far away from my keyboard, so I can take a look in two weeks.

What do you mean by "bugs"? You are saying that the weird (inconsistent) behavior appears only when you are having the color layout set by LED Custom Palette? Could you be more specifics?

I'm glad you like it! I hope we can solve this little issue. 💪

**Comment by goeland86** [comment]
@jukben not a worry - enjoy your time off! This isn't urgent, as I can just use the rainbow layout for now :)

It's probably easier if I shoot a video to demonstrate the effect but I'll try to summarize here:
- when hitting the `Fn` key (left or right) it switches to the alternate layout fine - but when releasing fails to revert to normal layout, as if key was still pressed
- when using a `Fn` + `macro key` combo, it sometimes stays active continually, even when released
- randomly when pressing and releasing `Fn` the right half of the keyboard loses all LED lighting when released, though keys behave normally.

When these issues are fixed I believe we'll have a winning firmware setup :+1:

**Comment by jukben** [comment]
Hey! I got finally closer to my Model01, I've refreshed the firmware (just to be sure) but I haven't seen any issue with Fn button. 😢 

Could you please update all submodules and try to flash it once more?

This might be something similar https://community.keyboard.io/t/macro-string-being-uppercased-unintentionally-arduino-boards-update/1914/9

**Comment by goeland86** [comment]
hmm, it's possible it was the same issue. Updated the arduino libraries and tried again, and yeah, Fn button issue is fixed.

Not your fault, and that's a good thing 👍
